### PR TITLE
Accept address and port as params on listen

### PR DESCRIPTION
**Pull request by harlanj**
As of now appy only grabs the address and port from file locations. Updated the `module.exports.listen` function to accept an address and port. If one is not provided then it will use set defaults after checking for the files that hold the address and port.

### CODE REVIEW

**Comment by boutell** [comment]
This is a good idea. However have you checked out that isNaN code you're
using carefully? isNaN does not mean "is not a reasonable number." It
means, very specifically, "is the result of a mathematical operation with
no possible number as an answer."

On Sun, Apr 5, 2015 at 6:30 AM, Jeremiah Harlan <notifications@github.com>
wrote:

> As of now appy only grabs the address and port from file locations.
> Updated the module.exports.listen function to accept an address and port.
> If one is not provided then it will use set defaults after checking for the
> files that hold the address and port.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/punkave/appy/pull/7
> Commit Summary
>
>    - accept params `address` and `port` on listen
>    - Move default address and port
>    - Update sample.js
>
> File Changes
>
>    - *M* appy.js <https://github.com/punkave/appy/pull/7/files#diff-0>
>    (32)
>
> Patch Links:
>
>    - https://github.com/punkave/appy/pull/7.patch
>    - https://github.com/punkave/appy/pull/7.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/appy/pull/7>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by harlanj** [comment]
Ah I see your point. I did a closer look at the documentation for it. I also forgot you're doing some RegEx after setting the port. Updated the code to just check if the port is set. Once these PRs get merged I'll submit my PRs for Apostrophe and Apostrophe-site to reflect this update.

**Comment by boutell** [comment]
Have you tested this with no host and port being passed? Does it definitely
maintain its classic behavior in that case?

On Mon, Apr 6, 2015 at 10:53 AM, Jeremiah Harlan <notifications@github.com>
wrote:

> Ah I see your point. I did a closer look at the documentation for it. I
> also forgot you're doing some RegEx after setting the port. Updated the
> code to just check if the port is set. Once these PRs get merged I'll
> submit my PRs for Apostrophe and Apostrophe-site to reflect this update.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/appy/pull/7#issuecomment-90087857>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by harlanj** [comment]
Absolutely. If no host/port is passed in and one cannot be found from the file location it then sets the host/port to a default value (same as it was before). I've updated `sample.js` to reflect the test

**Comment by boutell** [comment]
Looks like your pull request still does not include the commit that removes isNaN?

**Comment by harlanj** [comment]
https://github.com/harlanj/appy/blob/master/appy.js#L744

It should show there.

**Comment by boutell** [comment]
Just published this as 0.5.6. I also added support for passing only "port" (one argument).

**Comment by boutell** [comment]
Thanks for the contribution!

On Mon, Apr 6, 2015 at 1:07 PM, Jeremiah Harlan <notifications@github.com>
wrote:

> https://github.com/harlanj/appy/blob/master/appy.js#L744
>
> It should show there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/appy/pull/7#issuecomment-90158572>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by harlanj** [comment]
No problem. Just submitted my PR for apostrophe-site. https://github.com/punkave/apostrophe-site/pull/9

**Pull request merged**
